# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596a4280537e09228b5e6f37659b6baee83b402d81a98f88d601ec9900b61acdb41b00766764dd9f4b96349066170cbb2eb27064c2d175cb3fc604a076f808cd

test:
  secret_key_base: 86f4ecb6d96e0a809559b28f0107f310c1e9da6f63e879e69b13fd7fceeaa5e32b3e49562ca9db7d19b6b5b70918314dd444baa1b1d7362d3ef9d1b3b2edf286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
